USE ROLE TRANSFORM;
USE DATABASE AIRBNB_BERLIN;
USE SCHEMA DEV;

CREATE OR REPLACE TABLE LISTINGS_HOSTS AS
SELECT
    L.LISTING_ID,
    L.LISTING_NAME,
    L.ROOM_TYPE,
    L.MINIMUM_NIGHTS,
    L.PRICE,
    H.HOST_ID,
    H.HOST_NAME,
    H.IS_SUPERHOST
FROM
    AIRBNB_BERLIN.DEV.CLEANSED_LISTINGS AS L
LEFT JOIN
    AIRBNB_BERLIN.DEV.CLEANSED_HOSTS AS H
ON 
    L.HOST_ID = H.HOST_ID;